# Stephanie.Clay@dfo-mpo.gc.ca
# Aug 2025

# HARD-CODED FOR NWA OC-CCI v6.0 POLY4 AT 4.64KM RESOLUTION 39-66N 42-76W

# BASED ON CODE IN PANCAN_PROCESSING/WRITE_NETCDF.R

# https://wiki.esipfed.org/Category:Attribute_Conventions_Dataset_Discovery
# CF-1.6 attributes

# standard_name
# https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

# ioos_category:
# ioos_category.txt

# Compliance checker: https://compliance.ioos.us/index.html

# UDUNITS: https://docs.unidata.ucar.edu/udunits/current/

# https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-coordinate


#*******************************************************************************

make_att_list_mapped <- function(new_file, title, timeatt) {
    dc <- Sys.time()
    attr(dc,"tzone") <- "UTC"
    gatts <- list("product_name" = new_file,
                  "title" = title,
                  "date_created" = paste(format(dc,"%Y-%m-%d %H:%M:%S"),"UTC"),
                  "history" = "Created with map_and_write_to_netcdf.R. Input data were 4km-resolution spring bloom metrics and annual average chlorophyll-a (chl-a) concentration per bin. Bloom metrics for each bin and year were derived from a shifted gaussian curve fitted to the time series of daily logged chl-a data within that bin. Chl-a data were taken from the POLY4 chl-a dataset which was generated using remote sensing reflectances (Rrs) from the OC-CCI multisensor product (www.oceancolour.org) and regionally-tuned coefficients, and subsequently gap-filled using DINEOF (https://github.com/aida-alvera/DINEOF).",
                  "Conventions" = "CF-1.9",
                  "mission" = "Multiple missions",
                  "platform" = "Multiple platforms",
                  "sensor" = "Multiple sensors",
                  "reprocessing" = "v6.0",
                  "POLY4_coefficients" = "0.59779,-3.15824,-0.80348,0.93129,0.78322",
                  "temporal_range" = "year",
                  "time" = timeatt,
                  "region" = "Northwest Atlantic",
                  "processing_level" = "L4 Mapped",
                  "spatial_resolution" = "4.64km at equator",
                  "latitude_units" = "degrees_north",
                  "longitude_units" = "degrees_east",
                  "cdm_data_type" = "Grid",
                  "geographic_crs_epsg_code" = "EPSG:4326",
                  "projected_crs_epsg_code" = "EPSG:4087",
                  "map_projection" = "Equidistant Cylindrical (Plate Carrée)",
                  "northernmost_latitude" = 66,
                  "southernmost_latitude" = 39,
                  "easternmost_longitude" = -42,
                  "westernmost_longitude" = -76,
                  "geospatial_lat_max" = 66,
                  "geospatial_lat_min" = 39,
                  "geospatial_lat_resolution" = 0.04166667,
                  "geospatial_lat_units" = "degrees_north",
                  "geospatial_lon_max" = -42,
                  "geospatial_lon_min" = -76,
                  "geospatial_lon_resolution" = 0.04166667,
                  "geospatial_lon_units" = "degrees_east",
                  "source" = "Spring bloom metrics and annual average chlorophyll-a (chl-a) derived from DINEOF-filled POLY4 chl-a. POLY4 chl-a were created using remote sensing reflectance (Rrs) data from the OC-CCI multisensor product, which were generated by the Plymouth Marine Laboratory (PML) as part of the European Space Agency (ESA) climate change initiative (www.oceancolour.org).",
                  "creator_name" = "Stephanie Clay",
                  "creator_email" = "Stephanie.Clay@dfo-mpo.gc.ca",
                  "creator_group" = "SOPhyE (Satellite Ocean colour and Phytoplankton Ecology group), Ocean Monitoring and Modelling Section",
                  "institution" = "dfo_bio",
                  "references" = "doi:10.3390/s19194285; https://catalogue.ceda.ac.uk/uuid/690fdf8f229c4d04a2aa68de67beb733; doi:10.3390/rs11222609; Layton, C., Devred, E., DeTracey B.. 2022. A comparison of phytoplankton spring bloom fitting methods using MODIS satellite-derived chlorophyll-a concentration for the Maritimes region. Can. Tech. Rep. Hydrogr. Ocean Sci. 340: vii + 22 p.; Stephanie Clay, Chantelle Layton, & Emmanuel Devred. (2021). BIO-RSG/PhytoFit: First release (v1.0.0). Zenodo. https://doi.org/10.5281/zenodo.4770754; doi:10.1016/j.ocemod.2004.08.001",
                  "tools" = "https://github.com/BIO-RSG/oceancolouR",
                  "infoUrl" = "https://bio-rsg.github.io/",
                  "standard_name_vocabulary" = "CF Standard Name Table v79",
                  "keywords" = "Earth Science > Oceans > Ocean Chemistry > Chlorophyll; Earth Science > Oceans > Ocean Chemistry > Pigments > Chlorophyll; Earth Science > Oceans > Ocean Optics > Chlorophyll > Chlorophyll concentration; Providers > GOVERNMENT AGENCIES-NON-US > CANADA > CA/DFO/BIO; Platforms > Space-based Platforms > Earth Observation Satellites >",
                  "keywords_vocabulary" = "NASA Global Change Master Directory (GCMD) Science Keywords")
    return(gatts)
}
